services:
  db:
    image: mariadb:latest
    container_name: mariadb_container
    ports:
      - "3307:3307"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: 960720
      MYSQL_DATABASE: realEstate
    restart: unless-stopped
    privileged: true